"""empty message

Revision ID: e5d7b34e7072
Revises: 64fbaf111bed
Create Date: 2022-05-01 17:36:08.730515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5d7b34e7072'
down_revision = '64fbaf111bed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passwd_question', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('passwd_answer', sa.String(length=200), nullable=False))
        batch_op.drop_constraint('uq_user_agree', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_user_passwd_answer'), ['passwd_answer'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_passwd_question'), ['passwd_question'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])
        batch_op.drop_column('agree')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agree', sa.VARCHAR(length=60), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_passwd_question'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_passwd_answer'), type_='unique')
        batch_op.create_unique_constraint('uq_user_agree', ['agree'])
        batch_op.drop_column('passwd_answer')
        batch_op.drop_column('passwd_question')

    # ### end Alembic commands ###
